apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayExtension
metadata:
  name: global-ratelimit
  namespace: kgateway-system
spec:
  type: RateLimit
  rateLimit:
    grpcService:
      backendRef:
        name: ratelimit
        namespace: kgateway-system
        port: 8081
    timeout: "100ms"  # Optional timeout for rate limit service calls