apiVersion: v1
kind: Service
metadata:
  name: ratelimit
  namespace: kgateway-system
  labels:
    app: ratelimit
spec:
  ports:
  - port: 8081
    name: grpc
  selector:
    app: ratelimit
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratelimit
  namespace: kgateway-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratelimit
  template:
    metadata:
      labels:
        app: ratelimit
    spec:
      containers:
      - name: ratelimit
        image: envoyproxy/ratelimit:master
        env:
        - name: USE_STATSD
          value: "false"
        - name: LOG_LEVEL
          value: "debug"
        - name: RUNTIME_ROOT
          value: "/data"
        - name: RUNTIME_SUBDIRECTORY
          value: "ratelimit"
        - name: REDIS_SOCKET_TYPE
          value: "tcp"
        - name: REDIS_URL
          value: "redis:6379"
        - name: RUNTIME_WATCH_ROOT
          value: "false"
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: config-volume
          mountPath: /data/ratelimit/config
      volumes:
      - name: config-volume
        configMap:
          name: ratelimit-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
  namespace: kgateway-system
data:
  config.yaml: |
    domain: api-gateway
    descriptors:
      # Simple IP-based rate limit - 10 requests per minute per client IP
      - key: remote_address
        rate_limit:
          unit: minute
          requests_per_unit: 10
      # Path-based limits - 5 requests per minute to /api/restricted
      - key: path
        value: /api/restricted
        rate_limit:
          unit: minute
          requests_per_unit: 5
      # User-based limits with custom header
      - key: user_id
        rate_limit:
          unit: minute
          requests_per_unit: 100
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: kgateway-system
spec:
  ports:
  - port: 6379
    name: redis
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: kgateway-system
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379