apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  name: ip-rate-limit
  namespace: default
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: api-route
  rateLimit:
    global:
      domain: "api-gateway"
      descriptors:
      - key: "remote_address"
        valueFrom:
          remoteAddress: true
      extensionRef:
        name: global-ratelimit
      failOpen: false
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  name: path-based-rate-limit
  namespace: default
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: restricted-api-route
  rateLimit:
    global:
      domain: "api-gateway"
      descriptors:
      - key: "path"
        valueFrom:
          path: true
      extensionRef:
        name: global-ratelimit
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  name: user-based-rate-limit
  namespace: default
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: user-api-route
  rateLimit:
    global:
      domain: "api-gateway"
      descriptors:
      - key: "user_id"
        valueFrom:
          header: "X-User-ID"
      requestsPerUnit: 100
      unit: minute
      extensionRef:
        name: global-ratelimit
      failOpen: true
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  name: combined-rate-limit
  namespace: default
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: premium-api-route
  rateLimit:
    global:
      domain: "api-gateway"
      descriptors:
      - key: "user_id"
        valueFrom:
          header: "X-User-ID"
      - key: "service"
        value: "premium-api"
      extensionRef:
        name: global-ratelimit
    local:
      tokenBucket:
        maxTokens: 5
        tokensPerFill: 1
        fillInterval: "1s"