// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RateLimitApplyConfiguration represents a declarative configuration of the RateLimit type for use
// with apply.
type RateLimitApplyConfiguration struct {
	Local           *LocalRateLimitPolicyApplyConfiguration  `json:"local,omitempty"`
	GlobalRateLimit *GlobalRateLimitPolicyApplyConfiguration `json:"global,omitempty"`
}

// RateLimitApplyConfiguration constructs a declarative configuration of the RateLimit type for use with
// apply.
func RateLimit() *RateLimitApplyConfiguration {
	return &RateLimitApplyConfiguration{}
}

// WithLocal sets the Local field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Local field is set to the value of the last call.
func (b *RateLimitApplyConfiguration) WithLocal(value *LocalRateLimitPolicyApplyConfiguration) *RateLimitApplyConfiguration {
	b.Local = value
	return b
}

// WithGlobalRateLimit sets the GlobalRateLimit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GlobalRateLimit field is set to the value of the last call.
func (b *RateLimitApplyConfiguration) WithGlobalRateLimit(value *GlobalRateLimitPolicyApplyConfiguration) *RateLimitApplyConfiguration {
	b.GlobalRateLimit = value
	return b
}
