{{- range $entry := (list .Values.gatewayClass .Values.waypointClass) }}
{{- if $entry.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ $entry.name }}
  labels:
    {{- include "kgateway.labels" $ | nindent 4 }}
    {{- with $entry.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with $entry.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  controllerName: {{ $entry.controllerName }}
---
{{- end }}
{{- end }}
